os:
    - linux
    - osx

sudo: required

env:
    matrix:
        - SUBLIME_TEXT_VERSION="3"

script:
    - sh install_sublime_text.sh
    - sh install_package_control.sh

notifications:
    email:
        on_success: change
        on_failure: change
