environment:
    matrix:
        - SUBLIME_TEXT_VERSION : "2"
        - SUBLIME_TEXT_VERSION : "3"

build: off

test_script:
    - ps: .\install_sublime_text.ps1 -verbose
    - ps: .\install_package_control.ps1 -verbose
